// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 👇 Import the auto-injecting CTA panel
import AutoInspirationPanel from "@/components/AutoInspirationPanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Why No Website?",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // ✅ Make sure this file exists in /public
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* 👇 Inject the dynamic CTA globally */}
        <AutoInspirationPanel />
      </body>
    </html>
  );
}